### ISSUE TITLE
Can I be informed of code release?

### ISSUE THREAD

**Issue by TruthSearcher** [garibida/cross-image-attention#1]

**Comment by yuval-alaluf** [comment]
Hi. You can watch the repo and get alerts when there are new commits. We hope to have it out in a couple of weeks. :)

**Comment by Johnson-yue** [comment]
+1 waiting for it release

**Comment by justinday123** [comment]
please give me code !! thanks

**Comment by dgalor** [comment]
+1

**Comment by yuval-alaluf** [comment]
The code will be released in the coming days (along with a HuggingFace demo). 
We just want to make sure the code is of high quality 💪 
We appreciate everyone's patience 😄

**Comment by yuval-alaluf** [comment]
Enjoy the code :)
