### ISSUE TITLE
runwayml/stable-diffusion-v1-5 not found

### ISSUE THREAD

**Issue by miyangy** [garibida/cross-image-attention#17]
When running run.py, I can't load runwayml/stable-diffusion-v1-5, but the display of https://huggingface.co/API/models/RunwayML/stable-diffusion-v1-5 doesn't exist. Why?
![截图 2024-09-02 15-14-29](https://github.com/user-attachments/assets/2c16c380-d114-4ba7-9eb6-eb8e4b964972)

**Comment by danielgaribi** [comment]
The model weights were removed from Huggingface. You can use 1.4 instead:
https://huggingface.co/CompVis/stable-diffusion-v1-4
