### ISSUE TITLE
Some details

### ISSUE THREAD

**Issue by WANGSSSSSSS** [garibida/cross-image-attention#2]
Hi, guys, i have tried some similar techniques to transfer high frequency component of reference image, but my experiments not demonstrate comparable results to your projects 😢 , i want to figure out whether your algorithm employs cross-attention to replace all self attention layers or use some optimal choice ?

**Comment by yuval-alaluf** [comment]
Thanks for your interest :)
We actually don't switch the self-attention with the standard cross-attention. We introduce a new type of attention layer called cross-image attention which "swaps" the queries, keys, and values of two images. 
You can find out more in the paper and in the Appendix we provided some more implementation details. 
We'll try to publish the code as soon as possible.
