### ISSUE TITLE
Question on contrast augmentation

### ISSUE THREAD

**Issue by ethansmith2000** [garibida/cross-image-attention#3]
Hi there, I was reading through the paper and noticed it was mentioned that the initial attention maps from the cross-image attention attended to too many keys, and the contrasting served to fix this. I was wondering if it was tried to alternatively reduce the temperature of the softmax as to avoid negative values/ risking probabilities not summing to 1. But equally I could imagine a case for needing to increase overall weighting > 1 to increase effect. Curious if these were experimented with and any thoughts :)

**Comment by yuval-alaluf** [comment]
This is an interesting question. We did play with the exact contrasting operation (e.g., re-normalizing the outputs to make them sum to 1), but we didn't see any noticeable effect. Therefore, we decided to go with our simplest solution and simply use the contrast operation as is.
