### ISSUE TITLE
Bugs when setting "use_masked_adain = False"

### ISSUE THREAD

**Issue by FerryHuang** [garibida/cross-image-attention#6]
Thanks for your great works!
I was trying to find out how AdaIn trick works in the alg and launch the run.py with setting the `use_masked_adain = False` in config. And it reported `AttributeError: 'Segmentor' object has no attribute 'self_attention_32'` at sampling step20. 
I corrected [this line](https://github.com/garibida/cross-image-attention/blob/main/run.py#L49) with `callback=model.get_adain_callback if cfg.use_masked_adain else None,` and the run.py finished but it seemed that the **content** image contributed nothing to the synthesis image.
e.g.
![image](https://github.com/garibida/cross-image-attention/assets/71176040/5b00fe10-efa2-47f3-8afd-efbf98a13e49)
Please let me know if I overlooked any important details!

**Comment by yuval-alaluf** [comment]
It seems like you completely removed the use of the AdaIN by removing the callback, so this is something you'll want to keep. 
But now I did noticed that I removed the use of the non-masked AdaIN during the refactor :(
I'll try uploading a solution later today. Thanks for point this out :)

**Comment by yuval-alaluf** [comment]
Sorry for the delayed response, but I have just pushed a fix for running without masked adain (i.e., running with regular adain on the entire latent codes). 
Hope this helps, and thanks again for pointing this out!
